---
- name: Cau hinh tren Switch
  hosts: SW1
  gather_facts: no

  tasks:
    - name: tao vlan
      ios_vlan:
        aggregate:
          - { vlan_id : 10 }
          - { vlan_id : 20 }
          
    - name: gan cong vao vlan 10
      ios_config:
        parents:
          - int e0/2
        lines:
          - switchport mode access
          - switchport access vlan 10
          
    - name: gan cong vao vlan 10
      ios_config:
        parents:
          - int e0/2
        lines:
          - switchport mode access
          - switchport access vlan 20
        
    - name: chuyen cong e0/1 sang mode trunk
      ios_config:
        parents:
          - int e0/1
        lines:
          - sw trunk en dot1Q
          - sw mode trunk

- name: Cau hinh tren router
  hosts: R1
  gather_facts: no

  tasks:
    - name: Dat ip cho cong e0/1
      ios_config:
        parents:
          - int e0/1
        lines:
          - no shutdown
          - ip address 192.168.1.1 255.255.255.0

    - name: dat ip subinterface
      ios_config:
        parents:
          - int {{item.subint}}
        lines:
          - encapsulation dot1Q {{item.vlan}}
          - ip address 192.168.{{item.vlan}}.1 255.255.255.0
      with_items:
        - { subint: Ethernet0/1.10 , vlan: 10 }
        - { subint: Ethernet0/1.20 , vlan: 20 }

    - name: Show ip
      ios_command:
        commands:
          - show ip int brief
      register: show_ip

    - debug: var=show_ip.stdout_lines
